FROM l.gcr.io/google/ubuntu16_04
RUN echo "hey" > /Users/priyawadhwa/go/src/github.com/priyawadhwa/kbuild/exec/etc/foo
RUN echo "baz" > /Users/priyawadhwa/go/src/github.com/priyawadhwa/kbuild/exec/etc/foo
RUN echo "baz" > /Users/priyawadhwa/go/src/github.com/priyawadhwa/kbuild/exec/etc/foo2

COPY . foo